api/urls.py
from tastypie.api import Api

from django.conf.urls import patterns, include, url

from api import resources_v1


v1_api = Api(api_name='v1')
v1_api.register(resources_v1.UserResource())
v1_api.register(resources_v1.WorkPlaceResource())
v1_api.register(resources_v1.SquareResource())
v1_api.register(resources_v1.SettingsResource())


urlpatterns = patterns('',
    url(r'', include(v1_api.urls)),
)

base/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
    url(r'^', include('squares.urls')),
)

if settings.DEBUG:
    #urlpatterns += tuple(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True))
    urlpatterns += tuple(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True))

squares/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from squares.views import IndexView, WorkPlaceView, LoginView, LogoutView


urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^workplace/$', WorkPlaceView.as_view(), name='workplace'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    url(r'^files/uploader/$', 'squares.views.files_uploader', name='files-uploader'),
    url(r'^files/browser/$', 'squares.views.files_browser', name='files-browser'),

    url(r'^api/', include('api.urls')),
    url(r'^api/doc/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),

    url(r'^admin/', include(admin.site.urls)),
)

squares/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy


class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="%(app_label)s_%(class)s_owner")

    class Meta:
        abstract = True


class WorkPlace(BaseModel):
    name = models.CharField(max_length=255)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)
    background_image = models.CharField(max_length=255, default="/static/img/wallpaper.jpg")

    class Meta:
        verbose_name = ugettext_lazy(u'WorkPlace')
        verbose_name_plural = ugettext_lazy(u'WorkPlaces')

    def __unicode__(self):
        return u'%s' % self.name


class BaseSquare(BaseModel):
    COLOR_DEFAULT = '#E8E8E8'
    COLORS = (
        (COLOR_DEFAULT, 'Default'),
    )

    workplace = models.ForeignKey(WorkPlace, related_name="%(app_label)s_%(class)s_workplace")

    top = models.IntegerField(default=100)
    left = models.IntegerField(default=50)
    min_width = models.IntegerField(default=450)
    min_height = models.IntegerField(default=500)
    width = models.IntegerField(default=300)
    height = models.IntegerField(default=300)
    z_index = models.IntegerField(default=1)
    background_color = models.CharField(max_length=7, choices=COLORS, default=COLOR_DEFAULT)
    is_done = models.BooleanField(default=False)

    is_deleted = models.BooleanField(default=False)
    is_collapsed = models.BooleanField(default=False)
    is_expanded = models.BooleanField(default=False)

    title = models.CharField(max_length=255, default='new square')

    class Meta:
        abstract = True

    def __unicode__(self):
        return u'%s' % self.title


class Square(BaseSquare):
    data = models.TextField(default='')

    class Meta:
        verbose_name = ugettext_lazy(u'Square')
        verbose_name_plural = ugettext_lazy(u'Squares')


class Settings(BaseModel):
    
    class Meta:
        verbose_name = ugettext_lazy(u'Setting')
        verbose_name_plural = ugettext_lazy(u'Settings')

squares/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.utils.translation import ugettext_lazy

from squares.models import WorkPlace


class WorkplaceForm(forms.Form):
    workplace = forms.ModelChoiceField(queryset=WorkPlace.objects.none(), empty_label=None)

    def __init__(self, request, *args, **kwargs):
        super(WorkplaceForm, self).__init__(*args, **kwargs)
        self.fields['workplace'].queryset = WorkPlace.objects.filter(users=request.user)
        self.fields['workplace'].initial = request.workplace


class LoginForm(forms.Form):
    error_messages = {
        'invalid': ugettext_lazy(u'Username or password is not correct'),
    }

    username = forms.CharField(max_length=16, label=ugettext_lazy(u'Username'))
    password = forms.CharField(max_length=16, widget=forms.PasswordInput(), label=ugettext_lazy(u'Password'))
    user = None

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = ugettext_lazy(u'Username')
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = ugettext_lazy(u'Password')

    def clean(self):
        self.cleaned_data = super(LoginForm, self).clean()
        if 'password' in self.cleaned_data and 'username' in self.cleaned_data:
            self.user = authenticate(username=self.cleaned_data['username'], password=self.cleaned_data['password'])
            if not self.user:
                raise forms.ValidationError(self.error_messages['invalid'])
        return self.cleaned_data


class UploadFileForm(forms.Form):
    upload = forms.FileField()

api/views.py
from django.shortcuts import render

# Create your views here.

squares/views.py
import os
import json

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import logout, login
from django.shortcuts import redirect
from django.views.generic import TemplateView, FormView, RedirectView
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.http import HttpResponse

from squares.forms import LoginForm, UploadFileForm


class IndexView(TemplateView):
    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        return redirect(reverse_lazy('workplace'))


class WorkPlaceView(TemplateView):
    template_name = 'workplace.html'

    @method_decorator(login_required(login_url=reverse_lazy('login')))
    def dispatch(self, *args, **kwargs):
        return super(WorkPlaceView, self).dispatch(*args, **kwargs)


class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('workplace')

    def get_success_url(self):
        success_url = self.request.GET.get('next', None)
        if success_url is not None:
            return success_url
        return self.success_url

    def form_valid(self, form):
        login(self.request, form.user)
        return super(LoginView, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(self.success_url)
        return super(LoginView, self).dispatch(request, *args, **kwargs)


class LogoutView(RedirectView):
    url = reverse_lazy('index')

    def get_redirect_url(self):
        logout(self.request)
        return super(LogoutView, self).get_redirect_url()

    @method_decorator(login_required(login_url=reverse_lazy('login')))
    def dispatch(self, *args, **kwargs):
        return super(LogoutView, self).dispatch(*args, **kwargs)


@csrf_exempt
@login_required(login_url=reverse_lazy('login'))
def files_browser(request):
    pass


@csrf_exempt
@login_required(login_url=reverse_lazy('login'))
def files_uploader(request):
    def get_images_path(workplace, filename, root=settings.MEDIA_ROOT):
        try:
            root = '/squares/' + root
            os.makedirs(os.path.join(root, 'uploads', str(workplace.pk)))
        except Exception:
            pass
        return os.path.join(root, 'uploads', str(workplace.pk), filename)

    def handle_uploaded_file(workplace, f):
        path = get_images_path(workplace, f.name)
        with open(path, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        return get_images_path(workplace, f.name, root=settings.MEDIA_URL)

    if request.method == 'POST':
        path = ''
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            path = handle_uploaded_file(request.workplace, request.FILES['upload'])
    return HttpResponse(path, content_type="application/json")

squares/templates/base.html
{% load i18n %}
{% load staticfiles %}
{% load webdesign %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8">

    {% block extra-meta %}
    <title></title>
    {% endblock %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'select2/dist/css/select2.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block extra-css %}
    {% endblock %}
    </head>

    <body>
    <div class="se-pre-con"></div>

    {% block container %}
    {% endblock %} 

    {% block templates %}
    {% endblock %}

    <!-- script references -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/underscore-min.js' %}"></script>
    <script src="{% static 'js/backbone-min.js' %}"></script>
    <script src="{% static 'js/backbone-tastypie.js' %}"></script>
    <script src="{% static 'select2/dist/js/select2.min.js' %}"></script>

    <script type="text/javascript">
        $('select').select2();
        $("#id_workplace").change(function() {
            window.location.href = "?workplace_pk=" + $(this).val();
        });
    </script>

    {% block extra-js %}
    {% endblock %}
	</body>

</html>

squares/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load webdesign %}


{% block container %}
{% endblock %} 

squares/templates/login.html
{% extends 'squares.html' %}
{% load i18n %}
{% load staticfiles %}
{% load webdesign %}


{% block extra-css %}
  {{ block.super }}
  <link href="{% static 'css/bg.css' %}" rel="stylesheet">
{% endblock %}



{% block container %}
{{ block.super }}
<img src="/static/img/wallpaper.jpg" id="bg" alt="">
<div class="row" style="margin-top: 15%">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="login-panel panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title">{% trans 'Sign' %} <span class="glyphicon glyphicon-log-in pull-right" aria-hidden="true"></h3>
      </div>
      <div class="panel-body">
          <form role="form" method="post">
              {% csrf_token %}
              <fieldset>
                  <div class="form-group">
                      {{form.username}}
                  </div>
                  <div class="form-group">
                      {{form.password}}
                  </div>
                  <!-- Change this to a button or input when using this as a form -->
                  <button type="submit" class="btn btn-sm btn-success">{% trans 'Sign' %}</button>
              </fieldset>
          </form>
      </div>
    </div> 
  </div>
</div> 
{% endblock %} 

squares/templates/squares.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load webdesign %}

squares/templates/workplace.html
{% extends 'squares.html' %}

{% load i18n %}
{% load staticfiles %}
{% load webdesign %}


{% block extra-css %}
  {{ block.super }}
  <link href="{% static 'css/styles.css' %}" rel="stylesheet">
  <link href="{% static 'css/bg.css' %}" rel="stylesheet">
{% endblock %}


{% block container %}
{{ block.super }}
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <img src="{% static 'img/logo.gif' %}" alt="{{project}}" width=40 height=40 style="margin-top: 5px; float: left;">
        <a class="navbar-brand" href="#!/" style="float: left;">{{project}}</a>
        <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate" id="spin-loader" style="float: left;"></span>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left is-auth" role="search">
          <div class="form-group">
            {{workplace.workplace}}
          </div>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><button class="btn btn-default add-square" style="margin-top: 8px;margin-right: 15px;"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> {% trans 'square' %}</button></li>
          {% comment %}
          <li><a href="#!/settings"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a></li>
          <li><a href="#!/profile"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a></li>
          {% endcomment %}
          <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> {% trans 'на главную' %}</a></li>
          <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div id="container" class="container">
  </div>
{% endblock %} 


{% block templates %}
  <script type="text/template" id="workplace"> 
    <img src="<%= workplace.get('background_image') %>" id="bg" alt="">
    <div class="workplace">
        <div id="main">
        </div>
        <ul id="right-menu" class="nav nav-pills nav-stacked">
        </ul>
    </div>
  </script>

  <script type="text/template" id="square"> 
    <div class="square" data-id="<%= square.cid %>" style="
        position: absolute;
        top: <%= square.get('top') %>px;
        left: <%= square.get('left') %>px;
        z-index: <%= square.get('z_index') %>;
      ">
      <div class="panel panel-default draggable resizable ui-widget-content" style="
        min-width: <%= square.get('min_width') %>px;
        width: <%= square.get('width') %>px;
        min-height: <%= square.get('min_height') %>px;
        height: <%= square.get('height') %>px;
      ">
        <div class="panel-heading" style="
          height: 40px;
          background-image: linear-gradient(to bottom, #F5F5F5 0px, <%= square.get('background_color') %> 100%);
          background-color: <%= square.get('background_color') %>;
          ">
          <div class="pull-left draggable-handler">
            <span class="glyphicon glyphicon-move moving" aria-hidden="true"></span>
          </div>
          <div class="pull-left square-title" id="square-title-<%= square.get('id') %>">
            <% if (square.get('title_edit_mode')) { %>
              <input id="input-<%= square.get('id') %>" value="<%= square.get('title') %>">
              <span class="glyphicon glyphicon-floppy-disk action-title-save action pull-right" aria-hidden="true"></span>
            <% } else { %>
              <span class="title"><%= square.get('title') %></span>
            <% } %>
          </div>
          <div class="pull-right">
            <span class="glyphicon glyphicon-minus-sign action-collapse action" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-remove-sign action-remove action" aria-hidden="true"></span>
          </div>
        </div>
        <div class="panel-body square-data" >
          <% if (square.get('data_edit_mode')) { %>
            <textarea class="square-data-textarea" id="textarea-<%= square.get('id') %>"><%= square.get('data') %></textarea>
            <br>
            <span class="glyphicon glyphicon-floppy-disk action-data-save action pull-right" aria-hidden="true"></span>
          <% } else { %>
            <%= square.get('data') %>
          <% } %>
        </div>
      </div>
    </div>
  </script>

  <script type="text/template" id="item"> 
    <li>
      <button class="btn item" data-id="<%= item.cid %>" style="
        background-image: linear-gradient(to bottom, #F5F5F5 0px, <%= item.get('background_color') %> 100%);
        background-color: <%= item.get('background_color') %>;
        ">
        <% if (item.get('is_collapsed')) { %>
        <span class="glyphicon glyphicon-list-alt pull-left" aria-hidden="true"></span>
        <% } else { %>
        <span class="glyphicon glyphicon-record pull-left" aria-hidden="true"></span>
        <% } %>
        <span class="pull-right item-title"><%= item.get('title') %></span>
      </button>
    </li>
  </script>

  <script type="text/template" id="settings">
    <div class="row" style="margin-top: 5%;">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Settings <span class="glyphicon glyphicon-cog pull-right" aria-hidden="true"></h3>
          </div>
          <div class="panel-body">
              <form role="form">
                  <fieldset>
                      <div class="form-group">
                          <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus="">
                      </div>
                      <div class="form-group">
                          <input class="form-control" placeholder="Password" name="password" type="password" value="">
                      </div>
                      <!-- Change this to a button or input when using this as a form -->
                      <a href="javascript:;" class="btn btn-sm btn-success">Save</a>
                  </fieldset>
              </form>
          </div>
        </div> 
      </div>
    </div> 
  </script>

  <script type="text/template" id="profile">
    <div class="row" style="margin-top: 5%;">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Profile <span class="glyphicon glyphicon-user pull-right" aria-hidden="true"></h3>
          </div>
          <div class="panel-body">
              <form role="form">
                  <fieldset>
                      <div class="form-group">
                          <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus="">
                      </div>
                      <div class="form-group">
                          <input class="form-control" placeholder="Password" name="password" type="password" value="">
                      </div>
                      <!-- Change this to a button or input when using this as a form -->
                      <a href="javascript:;" class="btn btn-sm btn-success">Save</a>
                  </fieldset>
              </form>
          </div>
        </div> 
      </div>
    </div> 
  </script>
{% endblock %}


{% block extra-js %}
  {{ block.super }}
  <script src="{% static 'ckeditor/ckeditor.js' %}"></script>
  <script type="text/javascript">
        Backbone.Tastypie.apiKey.username = '{{user.username}}';
        Backbone.Tastypie.apiKey.key = '{{user.api_key.key}}';
        var currentWorkplacePk = '{{request.workplace.pk}}';
        var filebrowserUploadUrl = '{% url "files-uploader" %}';
        var filebrowserBrowseUrl = '{% url "files-browser" %}';
        var apiPrefix = '{{url_api_prefix}}';
  </script>
  <script src="{% static 'mvc/models.js' %}"></script>
  <script src="{% static 'mvc/collections.js' %}"></script>
  <script src="{% static 'mvc/views.js' %}"></script>
  <script src="{% static 'mvc/controllers.js' %}"></script>
{% endblock %}